# Generated by Django 3.2.5 on 2021-11-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='../assets/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(default='', upload_to='assets/<django.db.models.fields.CharField>/'),
        ),
    ]
