# Generated by Django 3.2.5 on 2021-11-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211125_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
