# Generated by Django 3.2.5 on 2021-12-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='videos/'),
        ),
    ]
